[build]
command = "ng build --configuration=production"
publish = "dist/expense-tracker/browser" # Update if your app's build folder is named differently
base = "/"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
